from matplotlib import pyplot as plt

class position:
    def __init__(self, x, y):
        self.x = x
        self.y = y

class electrode:
    def __init__(self, label="label", position=position(x=0,y=0)):
        self.label = label
        self.position = position

class MEA:
    def __init__(self, electrodes=[]):
        self.electrodes = electrodes
    def addElectrode(self, electrode):
        self.electrodes.append(electrode)
    def getElectrode(self, label):
        for e in self.electrodes:
            if e.label == label:
                return e
        return electrodes("N/A", position(0,0))
    def show(self):
        h = plt.figure()
        a = h.add_subplot(111)
        for e in self.electrodes:
            a.plot(e.position.x, e.position.y, 'o', color='black', ms=1, alpha=0.0)
            a.text(e.position.x, e.position.y, str(e.label), color='black', horizontalalignment='center', verticalalignment='center')
        plt.show()

HDMEA = MEA([])
HDMEA.addElectrode(electrode(label="A1", position=position(x=-2.0*40, y= 4.0*40)))
HDMEA.addElectrode(electrode(label="A2", position=position(x=-1.0*40, y= 4.0*40)))
HDMEA.addElectrode(electrode(label="A3", position=position(x= 0.0*40, y= 4.0*40)))
HDMEA.addElectrode(electrode(label="A4", position=position(x= 1.0*40, y= 4.0*40)))
HDMEA.addElectrode(electrode(label="A5", position=position(x= 2.0*40, y= 4.0*40)))
HDMEA.addElectrode(electrode(label="B1", position=position(x=-2.5*40, y= 3.0*40)))
HDMEA.addElectrode(electrode(label="B2", position=position(x=-1.5*40, y= 3.0*40)))
HDMEA.addElectrode(electrode(label="B3", position=position(x=-0.5*40, y= 3.0*40)))
HDMEA.addElectrode(electrode(label="B4", position=position(x= 0.5*40, y= 3.0*40)))
HDMEA.addElectrode(electrode(label="B5", position=position(x= 1.5*40, y= 3.0*40)))
HDMEA.addElectrode(electrode(label="B6", position=position(x= 2.5*40, y= 3.0*40)))
HDMEA.addElectrode(electrode(label="C1", position=position(x=-3.0*40, y= 2.0*40)))
HDMEA.addElectrode(electrode(label="C2", position=position(x=-2.0*40, y= 2.0*40)))
HDMEA.addElectrode(electrode(label="C3", position=position(x=-1.0*40, y= 2.0*40)))
HDMEA.addElectrode(electrode(label="C4", position=position(x= 0.0*40, y= 2.0*40)))
HDMEA.addElectrode(electrode(label="C5", position=position(x= 1.0*40, y= 2.0*40)))
HDMEA.addElectrode(electrode(label="C6", position=position(x= 2.0*40, y= 2.0*40)))
HDMEA.addElectrode(electrode(label="C7", position=position(x= 3.0*40, y= 2.0*40)))
HDMEA.addElectrode(electrode(label="D1", position=position(x=-3.5*40, y= 1.0*40)))
HDMEA.addElectrode(electrode(label="D2", position=position(x=-2.5*40, y= 1.0*40)))
HDMEA.addElectrode(electrode(label="D3", position=position(x=-1.5*40, y= 1.0*40)))
HDMEA.addElectrode(electrode(label="D4", position=position(x=-0.5*40, y= 1.0*40)))
HDMEA.addElectrode(electrode(label="D5", position=position(x= 0.5*40, y= 1.0*40)))
HDMEA.addElectrode(electrode(label="D6", position=position(x= 1.5*40, y= 1.0*40)))
HDMEA.addElectrode(electrode(label="D7", position=position(x= 2.5*40, y= 1.0*40)))
HDMEA.addElectrode(electrode(label="D8", position=position(x= 3.5*40, y= 1.0*40)))
HDMEA.addElectrode(electrode(label="E1", position=position(x=-3.0*40, y= 0.0*40)))
HDMEA.addElectrode(electrode(label="E2", position=position(x=-2.0*40, y= 0.0*40)))
HDMEA.addElectrode(electrode(label="E3", position=position(x=-1.0*40, y= 0.0*40)))
HDMEA.addElectrode(electrode(label="E4", position=position(x=-0.0*40, y= 0.0*40)))
HDMEA.addElectrode(electrode(label="E5", position=position(x= 1.0*40, y= 0.0*40)))
HDMEA.addElectrode(electrode(label="E6", position=position(x= 2.0*40, y= 0.0*40)))
HDMEA.addElectrode(electrode(label="E7", position=position(x= 3.0*40, y= 0.0*40)))
HDMEA.addElectrode(electrode(label="F1", position=position(x=-3.5*40, y=-1.0*40)))
HDMEA.addElectrode(electrode(label="F2", position=position(x=-2.5*40, y=-1.0*40)))
HDMEA.addElectrode(electrode(label="F3", position=position(x=-1.5*40, y=-1.0*40)))
HDMEA.addElectrode(electrode(label="F4", position=position(x=-0.5*40, y=-1.0*40)))
HDMEA.addElectrode(electrode(label="F5", position=position(x= 0.5*40, y=-1.0*40)))
HDMEA.addElectrode(electrode(label="F6", position=position(x= 1.5*40, y=-1.0*40)))
HDMEA.addElectrode(electrode(label="F7", position=position(x= 2.5*40, y=-1.0*40)))
HDMEA.addElectrode(electrode(label="F8", position=position(x= 3.5*40, y=-1.0*40)))
HDMEA.addElectrode(electrode(label="G1", position=position(x=-3.0*40, y=-2.0*40)))
HDMEA.addElectrode(electrode(label="G2", position=position(x=-2.0*40, y=-2.0*40)))
HDMEA.addElectrode(electrode(label="G3", position=position(x=-1.0*40, y=-2.0*40)))
HDMEA.addElectrode(electrode(label="G4", position=position(x= 0.0*40, y=-2.0*40)))
HDMEA.addElectrode(electrode(label="G5", position=position(x= 1.0*40, y=-2.0*40)))
HDMEA.addElectrode(electrode(label="G6", position=position(x= 2.0*40, y=-2.0*40)))
HDMEA.addElectrode(electrode(label="G7", position=position(x= 3.0*40, y=-2.0*40)))
HDMEA.addElectrode(electrode(label="H1", position=position(x=-2.5*40, y=-3.0*40)))
HDMEA.addElectrode(electrode(label="H2", position=position(x=-1.5*40, y=-3.0*40)))
HDMEA.addElectrode(electrode(label="H3", position=position(x=-0.5*40, y=-3.0*40)))
HDMEA.addElectrode(electrode(label="H4", position=position(x= 0.5*40, y=-3.0*40)))
HDMEA.addElectrode(electrode(label="H5", position=position(x= 1.5*40, y=-3.0*40)))
HDMEA.addElectrode(electrode(label="H6", position=position(x= 2.5*40, y=-3.0*40)))
HDMEA.addElectrode(electrode(label="J1", position=position(x=-2.0*40, y=-4.0*40)))
HDMEA.addElectrode(electrode(label="J2", position=position(x=-1.0*40, y=-4.0*40)))
HDMEA.addElectrode(electrode(label="J3", position=position(x= 0.0*40, y=-4.0*40)))
HDMEA.addElectrode(electrode(label="J4", position=position(x= 1.0*40, y=-4.0*40)))
HDMEA.addElectrode(electrode(label="J5", position=position(x= 2.0*40, y=-4.0*40)))

MEA_ElTesto = MEA([])
MEA_ElTesto.addElectrode(electrode(label="ElA1", position=position(x=-2.0*40, y= 4.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElA2", position=position(x=-1.0*40, y= 4.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElA3", position=position(x= 0.0*40, y= 4.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElA4", position=position(x= 1.0*40, y= 4.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElA5", position=position(x= 2.0*40, y= 4.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElB1", position=position(x=-2.5*40, y= 3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElB2", position=position(x=-1.5*40, y= 3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElB3", position=position(x=-0.5*40, y= 3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElB4", position=position(x= 0.5*40, y= 3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElB5", position=position(x= 1.5*40, y= 3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElB6", position=position(x= 2.5*40, y= 3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElC1", position=position(x=-3.0*40, y= 2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElC2", position=position(x=-2.0*40, y= 2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElC3", position=position(x=-1.0*40, y= 2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElC4", position=position(x= 0.0*40, y= 2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElC5", position=position(x= 1.0*40, y= 2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElC6", position=position(x= 2.0*40, y= 2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElC7", position=position(x= 3.0*40, y= 2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElD1", position=position(x=-3.5*40, y= 1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElD2", position=position(x=-2.5*40, y= 1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElD3", position=position(x=-1.5*40, y= 1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElD4", position=position(x=-0.5*40, y= 1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElD5", position=position(x= 0.5*40, y= 1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElD6", position=position(x= 1.5*40, y= 1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElD7", position=position(x= 2.5*40, y= 1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElD8", position=position(x= 3.5*40, y= 1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElE1", position=position(x=-3.0*40, y= 0.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElE2", position=position(x=-2.0*40, y= 0.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElE3", position=position(x=-1.0*40, y= 0.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElE4", position=position(x=-0.0*40, y= 0.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElE5", position=position(x= 1.0*40, y= 0.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElE6", position=position(x= 2.0*40, y= 0.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElE7", position=position(x= 3.0*40, y= 0.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElF1", position=position(x=-3.5*40, y=-1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElF2", position=position(x=-2.5*40, y=-1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElF3", position=position(x=-1.5*40, y=-1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElF4", position=position(x=-0.5*40, y=-1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElF5", position=position(x= 0.5*40, y=-1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElF6", position=position(x= 1.5*40, y=-1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElF7", position=position(x= 2.5*40, y=-1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElF8", position=position(x= 3.5*40, y=-1.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElG1", position=position(x=-3.0*40, y=-2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElG2", position=position(x=-2.0*40, y=-2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElG3", position=position(x=-1.0*40, y=-2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElG4", position=position(x= 0.0*40, y=-2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElG5", position=position(x= 1.0*40, y=-2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElG6", position=position(x= 2.0*40, y=-2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElG7", position=position(x= 3.0*40, y=-2.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElH1", position=position(x=-2.5*40, y=-3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElH2", position=position(x=-1.5*40, y=-3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElH3", position=position(x=-0.5*40, y=-3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElH4", position=position(x= 0.5*40, y=-3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElH5", position=position(x= 1.5*40, y=-3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElH6", position=position(x= 2.5*40, y=-3.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElJ1", position=position(x=-2.0*40, y=-4.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElJ2", position=position(x=-1.0*40, y=-4.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElJ3", position=position(x= 0.0*40, y=-4.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElJ4", position=position(x= 1.0*40, y=-4.0*40)))
MEA_ElTesto.addElectrode(electrode(label="ElJ5", position=position(x= 2.0*40, y=-4.0*40)))

if __name__ == "__main__":
    HDMEA.show()
    MEATEST.show()
